---
- name: creating a folder and a file into this folder
  hosts: all
  become: true
  gather_facts: no

  tasks: 
  - name: create a folder
    file: 
      path: /home/jenkins/playbooks/test-directory-from-jenkins
      state: directory
      mode: 0755
      owner: jenkins
      group: jenkins
  - name: create a file into the recently created folder
    file: 
      path: /home/jenkins/playbooks/test-directory-from-jenkins/testfile-from-jenkins.txt
      state: touch
      mode: 0755
      owner: jenkins
      group: jenkins
